/*
 * Generated by ISE 15.12.9.8497 GPL Edition - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F191_4581();
extern void F195_4844();
extern void F189_4508();
extern void F194_4753();
extern void F272_2578();
extern void F229_4388();
extern void F27_585();
extern EIF_REFERENCE F27_572();
extern EIF_BOOLEAN F27_584();
extern EIF_BOOLEAN F27_589();
extern void F27_594();
extern void F27_595();
extern void F27_596();
extern void F43_904();
extern EIF_TYPED_VALUE F43_905();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F191_4581;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F189_4508;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F272_2578;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F195_4844;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F194_4753;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F229_4388;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F27_585;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F27_584;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F27_572;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F27_589;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F27_594;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F27_595;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F27_596;

	egc_str_dtype = 194;

	egc_str32_dtype = 193;
	egc_arr_dtype = 271;
	egc_tup_dtype = 143;
	egc_disp_rout_id = 766;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0191;
	egc_sp_wchar = 0x0236;
	egc_sp_bool = 0x01AE;
	egc_sp_uint8 = 0x0156;
	egc_sp_uint16 = 0x0296;
	egc_sp_uint32 = 0x02B2;
	egc_sp_uint64 = 0x01E1;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0xF5;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x0174;
	egc_sp_real64 = 0x02CF;
	egc_sp_pointer = 0x0279;
	egc_sp_ref = 0x0109;

	egc_uint8_dtype = 163;
	egc_uint16_dtype = 160;
	egc_uint32_dtype = 157;
	egc_uint64_dtype = 154;
	egc_int8_dtype = 151;
	egc_int16_dtype = 148;
	egc_int32_dtype = 181;
	egc_int64_dtype = 145;
	egc_bool_dtype = 178;
	egc_real32_dtype = 166;
	egc_char_dtype = 175;
	egc_wchar_dtype = 172;
	egc_real64_dtype = 169;
	egc_point_dtype = 184;

	egc_exception_dtype = 63;
	egc_except_emnger_dtype = 26;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "mymap";
	egc_system_location = "C:\\Users\\Owner\\Downloads\\3311_a1\\MyMap\\EIFGENs\\mymap\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1466747736;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 766;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1120;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 42;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F43_904;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F43_905;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 57; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
